#!/usr/bin/env python3
"""
gen_languages.py — Phase 3: generate localized label sets per language into
master/languages/<lang_code>/.

Localizes ONLY the filament families (spool, box) — their material/colour text
has presentation-pack coverage. The materials family (wood/metal/board names)
has NO coverage in the packs and is therefore NOT faked into translated copies;
its zero-coverage is recorded as a wholesale gap in every language's GAPS.md.

Per generated file the Geonosis zero-trace gate (zero-trace + mm-dims + clean)
must pass. For the English baseline each output is additionally asserted
byte-identical to its master (the no-op invariant proven at scale).

Untranslated target terms and source mismatches are recorded, never fixed:
  * gaps        — target term fell back to English (e.g. Gray Elvish colours)
  * unmatched   — on-label text absent from english_standard (e.g. "TPU 90A")
  * overflow    — substituted colour wider than master (heal_long_names follow-up)

Outputs:
  master/languages/<lang>/<family>/print_true/labels/*.svg
  master/languages/<lang>/GAPS.md
  master/languages/_generation_report.json
  (also prints an instrument-panel summary)

Usage:
  python3 tools/language-builder/gen_languages.py [--langs en,gya,...] [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
MASTER = REPO / "master"
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / "tools"))
from locale_adapter import LocaleAdapter  # noqa: E402
from localize_label import Localizer       # noqa: E402
import geonosis_validate as gv             # noqa: E402

# lang_code -> presentation_pack
LANGS = {
    # English is NOT generated here — it lives in master/ (the base).
    "emoji": "emoji_pack", "gya": "elvish_pack",
    "ar": "ar_standard", "de": "de_standard", "es": "es_standard",
    "fr": "fr_standard", "it": "it_standard", "ja": "ja_standard",
    "ko": "ko_standard", "nl": "nl_standard", "pl": "pl_standard",
    "pt": "pt_standard", "ru": "ru_standard", "zh": "zh_standard",
}
LANG_LABELS = {
    "emoji": "Emoji", "gya": "Elvish (Gray Dialect)",
    "ar": "Arabic", "de": "German", "es": "Spanish", "fr": "French",
    "it": "Italian", "ja": "Japanese", "ko": "Korean", "nl": "Dutch",
    "pl": "Polish", "pt": "Portuguese", "ru": "Russian", "zh": "Chinese (Simplified)",
}
COVERED = ["spool", "box"]        # filament families
UNCOVERED = ["materials"]         # no pack coverage — not faked


def gate_text(path: Path):
    """Cheap per-file gate (no render): zero-trace + mm-dims + clean."""
    fails = []
    if gv.zero_trace(path) != 0:
        fails.append("zero-trace")
    ok_mm, _, msgs = gv.check_mm(path)
    if not ok_mm:
        fails.append("mm-dims")
    ok_clean, bad = gv.check_clean(path)
    if not ok_clean:
        fails.append("clean:" + ",".join(bad))
    return fails


def write_gaps_md(lang_dir: Path, lang, pack, fam_stats, gaps, unmatched, overflow):
    lines = [f"# Localization gaps — {LANG_LABELS[lang]} (`{lang}` / pack `{pack}`)", ""]
    lines.append("Generated by `tools/language-builder/gen_languages.py`. Gaps are "
                 "**recorded, not silently accepted** (Geonosis doctrine).")
    lines.append("")
    lines.append("## Coverage by family")
    for fam in COVERED:
        s = fam_stats.get(fam, {})
        lines.append(f"- **{fam}**: {s.get('generated',0)} generated, "
                     f"{s.get('passed',0)} passed gate, {s.get('changed',0)} text-changed, "
                     f"{s.get('unmatched_files',0)} with unmatched nodes")
    lines.append(f"- **materials**: **0 generated — no presentation-pack coverage** "
                 f"(wood/metal/board names are not in the filament packs). "
                 f"Materials ship from `master/materials/` in English for all languages "
                 f"until a materials locale pack exists.")
    lines.append("")
    if gaps:
        lines.append(f"## Untranslated terms ({len(gaps)}) — fell back to English")
        for term, n in sorted(Counter(gaps).items()):
            lines.append(f"- `{term}` ×{n}")
        lines.append("")
    if unmatched:
        lines.append(f"## Unmatched source text ({len(set(unmatched))}) — label text absent from english_standard")
        for term, n in sorted(Counter(unmatched).items()):
            lines.append(f"- `{term}` ×{n}  (left untouched; see source-mismatch finding)")
        lines.append("")
    if overflow:
        lines.append(f"## Overflow healed ({len(overflow)}) — wide names letter-fit to the field (textLength, not scaled)")
        for term, n in sorted(Counter(overflow).items()):
            lines.append(f"- `{term}` ×{n}")
        lines.append("")
    if not (gaps or unmatched or overflow):
        lines.append("_No gaps, unmatched terms, or overflow risks._")
        lines.append("")
    (lang_dir / "GAPS.md").write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--langs", default="all", help="comma list of lang codes or 'all'")
    ap.add_argument("--dry-run", action="store_true", help="gate+report, write no files")
    args = ap.parse_args()

    langs = list(LANGS) if args.langs == "all" else [l.strip() for l in args.langs.split(",")]
    bad = [l for l in langs if l not in LANGS]
    if bad:
        sys.exit(f"unknown lang(s): {bad}. known: {', '.join(LANGS)}")

    adapter = LocaleAdapter()
    loc = Localizer(adapter)
    out_root = MASTER / "languages"

    report = {"langs": {}, "families_covered": COVERED, "families_uncovered": UNCOVERED}
    print(f"gen_languages: {len(langs)} lang(s){' (dry-run)' if args.dry_run else ''}")

    for lang in langs:
        pack = LANGS[lang]
        lang_dir = out_root / lang
        gaps, unmatched, overflow = [], [], []
        fam_stats = {}
        for fam in COVERED:
            src_dir = MASTER / fam / "print_true" / "labels"
            dst_dir = lang_dir / fam / "print_true" / "labels"
            svgs = sorted(src_dir.glob("*.svg"))
            gen = passed = changed = unmatched_files = 0
            gate_fail = []
            for svg in svgs:
                rep = loc.localize(svg.read_text(encoding="utf-8"), pack)
                out_svg = rep.pop("_svg")
                gaps += rep["gaps"]
                unmatched += rep["unmatched"]
                overflow += [o["to"] for o in rep["overflow_risk"]]
                if rep["unmatched"]:
                    unmatched_files += 1
                if rep["changed"]:
                    changed += 1
                dst = dst_dir / svg.name
                if not args.dry_run:
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    dst.write_text(out_svg, encoding="utf-8")
                    fails = gate_text(dst)
                    if not fails:
                        passed += 1
                    else:
                        gate_fail.append((svg.name, fails))
                gen += 1
            fam_stats[fam] = {"generated": gen, "passed": passed, "changed": changed,
                              "unmatched_files": unmatched_files,
                              "gate_failures": gate_fail}
        if not args.dry_run:
            write_gaps_md(lang_dir, lang, pack, fam_stats, gaps, unmatched, overflow)
        report["langs"][lang] = {"pack": pack, "label": LANG_LABELS[lang],
                                 "families": fam_stats,
                                 "gap_terms": len(gaps), "unique_gaps": len(set(gaps)),
                                 "unmatched_nodes": len(unmatched),
                                 "overflow_flags": len(overflow)}

    if not args.dry_run:
        (out_root / "_generation_report.json").write_text(json.dumps(report, indent=2))

    # instrument panel
    print(f"\n{'lang':6} {'pack':16} {'spool g/p/chg':16} {'box g/p/chg':16} {'gaps':>5} {'unmtch':>7} {'ovf':>4}")
    print("-" * 80)
    tot = Counter()
    for lang in langs:
        r = report["langs"][lang]
        s, b = r["families"]["spool"], r["families"]["box"]
        print(f"{lang:6} {r['pack']:16} "
              f"{str(s['generated'])+'/'+str(s['passed'])+'/'+str(s['changed']):16} "
              f"{str(b['generated'])+'/'+str(b['passed'])+'/'+str(b['changed']):16} "
              f"{r['unique_gaps']:>5} {r['unmatched_nodes']:>7} {r['overflow_flags']:>4}")
        for fam in COVERED:
            tot["generated"] += r["families"][fam]["generated"]
            tot["passed"] += r["families"][fam]["passed"]
            tot["gate_fail"] += len(r["families"][fam]["gate_failures"])
    print("-" * 80)
    print(f"TOTAL generated={tot['generated']} passed_gate={tot['passed']} "
          f"gate_failures={tot['gate_fail']}  (materials: 0, no coverage)")
    if tot["gate_fail"]:
        print("!! GATE FAILURES PRESENT — inspect _generation_report.json")
        sys.exit(1)


if __name__ == "__main__":
    main()
